sudo: required
services:
  - docker

before_install:
  - docker build -t 539904/docker-react -f Dockerfile.dev .

script:
  - docker run 539904/docker-react npm run test -- --coverage
  # - docker run -e CI=true 539904/docker-react npm run test